### ISSUE TITLE
Multi-domain reverse proxy

### ISSUE THREAD

**Issue by d47081** [omar-polo/gmid#22]
Hello, 

I want to use single IPv4 to make proxy for 2 domains, but on defining 2 servers as on example - get certificate mismatch

```
server "betahowto.duckdns.org" {
	listen on 94.140.114.89 port 1965
	cert "/home/gmid/betahowto.duckdns.org/cert.pem"
	key "/home/gmid/betahowto.duckdns.org/key.rsa"

	proxy {
		relay-to 301:5eb5:f061:678e::b port 1965
		verifyname off
	}
}

server "kevachat.duckdns.org" {
	listen on 94.140.114.89 port 1965
	cert "/home/gmid/kevachat.duckdns.org/cert.pem"
	key "/home/gmid/kevachat.duckdns.org/key.rsa"

	proxy {
		relay-to 201:23b4:991a:634d:8359:4521:5576:15b7 port 1965
		verifyname off
	}
}
```

**Comment by omar-polo** [comment]
Hello, thanks for the report.

The configuration seems correct to me.

I believe the certificate error comes from the upstream server, the one listening at the IPv6 addresses.  When using a IP address (v4 or v6 doesn't matter) in a `relay-to` directive, the SNI (the remote server name) is missing and should be specified in the configuration file.  I should point this out in the documentation.

Do you still get errors when specifying the remote server name using the `sni` directive in the proxy block, for e.g.:

```
proxy {
	relay-to 301:5eb5:f061:678e::b port 1965
	verifyname off
	sni "remote-server-name"
}
```

`verifyname off` only applies to gmid-the-proxy itself, it won't complain if the certificate used by the upstream server doesn't match what it expects, but doesn't stop the upstream server from complaining that there's a missing SNI.

**Comment by omar-polo** [comment]
Happy to know that it worked :)  I'll try to make the documentation more clear in this regard.

Thanks

**Comment by omar-polo** [comment]
Not sure, as I never really considered this use-case, but maybe something like:

```
server "*" {
	# certs, key omitted
}
```
