### ISSUE TITLE
Wrong usage helps

### ISSUE THREAD

**Issue by sikmir** [omar-polo/gmid#35]
* Should be titan instead of gmid:
```sh
$ results/gmid/bin/titan
usage: gmid [-C cert] [-K key] [-m mime] [-t token] url [file]
```
* Should be gg instead of gmid:
```sh
$ results/gmid/bin/gg
version: gg 2.1
usage: gmid [-23Nnq] [-C cert] [-d mode] [-H sni] [-K key] [-P host[:port]]
          [-T seconds] gemini://...
```
* Should be gemexp instead of gmid:
```sh
$ results/gmid/bin/gemexp -h
Version: gemexp 2.1
Usage: gmid [-hRV] [-d certs-dir] [-H hostname] [-p port] [dir]
```

**Comment by omar-polo** [comment]
Ooops, the `getprogname` compat was broken since the `HAVE_*` values are not propagated to the generated `config.h`.  I think I've fixed it in https://github.com/omar-polo/gmid/issues/35, could you please confirm that it works for you?

Thanks!

**Comment by sikmir** [comment]
> I think I've fixed it in https://github.com/omar-polo/gmid/commit/0cf61ffcaf5321ee5888f5c1d247a1c383ff75fd, could you please confirm that it works for you?

It's fine now:
```sh
$ result/bin/titan
usage: titan [-C cert] [-K key] [-m mime] [-t token] url [file]
$ result/bin/gg
version: gg 2.0.5
usage: gg [-23Nnq] [-C cert] [-d mode] [-H sni] [-K key] [-P host[:port]]
          [-T seconds] gemini://...
$ result/bin/gemexp -h
Version: gemexp 2.0.5
Usage: gemexp [-hRV] [-d certs-dir] [-H hostname] [-p port] [dir]
$ result/bin/gmid -h
Version: gmid 2.0.5
Usage: gmid [-fnv] [-c config] [-D macro=value] [-P pidfile]
```

**Comment by omar-polo** [comment]
Thanks for the report and for testing the fix :)
