### ISSUE TITLE
Missing slash in access log file

### ISSUE THREAD

**Issue by chenein** [omar-polo/gmid#39]
The logfile roughly follows the common log format, but there is a missing slash between the month and year:

domain.com 1.2.3.4 - - 29/Aug2024:08:26:41 -0400 "gemini://domain.com/" 20 0

I think you meant:

domain.com 1.2.3.4 - - 29/Aug/2024:08:26:41 -0400 "gemini://domain.com/" 20 0

**Comment by omar-polo** [comment]
Thank you for the report!  It was just a typo, now fixed and will be part of the next release.

P.S.: while here, the 0 is because gmid at the moment logs the request when it is handled, not when it is completed, so it doesn't know the body size.  This will be fixed.
